import Head from "next/head"
import Informacoes from "../components/informacoes"
import { main } from "framer-motion/m"
import Header from "../components/header";
import Title from "../components/title";
import Footer from "../components/footer";
import ButtonAtividade from "@/components/buttonAtividade";





export default function Home() {
  return (
    <>
        <main>
        <Head>
        <title>Mural de atividades</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       </Head>

        <Header />
        <Title />
        <hr />
        <ButtonAtividade />
        <Informacoes />
        <Footer />
        </main>
    </>
  )
}
